version: '3.9'
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./.docker/postgres/:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=docker

  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
    networks:
      - network

networks:
  network:
    driver: bridge